version: '3.8'

services:
  api:
    build: .
    network_mode: host  # host mode for test
    environment:
      - TEST_QUEST_DB_HOST=${TEST_QUEST_DB_HOST}  
      - TEST_QUEST_DB_PORT=${TEST_QUEST_DB_HOST}
      - TEST_QUEST_DB_NAME=${TEST_QUEST_DB_NAME}
      - TEST_QUEST_DB_LOGIN=${TEST_QUEST_DB_LOGIN}
      - TEST_QUEST_DB_PASSWORD=${TEST_QUEST_DB_PASSWORD}
      - TEST_QUEST_API_HOST=${TEST_QUEST_API_HOST:-0.0.0.0}
      - TEST_QUEST_API_PORT=${TEST_QUEST_API_PORT:-8000}
    volumes:
      - .:/app
    command: >
      sh -c "sleep 5 &&
             alembic upgrade head &&
             python main.py"
